### PR TITLE
Changing isset to array_key_exists to address null options as in #5

### PR DESCRIPTION
**Pull request by Lansoweb**
For instance, the 'lang' option is null per default (auto-detect), so you can never set it through constructor because of the isset check. Changing to array_key_exists solves this problem.

### CODE REVIEW

**Comment by samsonasik** [comment]
travis build failures, please provide unit tests.

**Comment by Lansoweb** [comment]
@samsonasik Yes, just saw it. Will fix the tests and create a new one for this functionality.

**Comment by samsonasik** [comment]
:+1:

**Comment by Lansoweb** [comment]
@samsonasik Lesson learned: NEVER create a PR in a hurry :) Fixing the code ...

**Comment by Lansoweb** [comment]
@samsonasik Ok, all tests passing now. Thanks!

**Comment by Maks3w** [comment]
Need tests

**Comment by Lansoweb** [comment]
@Maks3w Test included and passing. Sorry for the delay.

**Comment by Maks3w** [comment]
@weierophinney Could you evaluate this?

**Comment by samsonasik** [comment]
ping @weierophinney

**Pull request merged**
